Found Diamonds Configuration:
  Main:
    Disable in creative mode: true
    Give OPs all permissions: true
  Light Level:
    Minimum amount of light required to mine blocks: 10%
    Monitored Blocks:
  Traps:
    Kick players on trap break: true
    Ban players on trap break: false
    Admin alerts on all trap breaks: false
    Kick message: You broke a FoundDiamonds trap block.
  Awards:
    Items:
      Award all players: true
      Random items for finding diamonds: false
      Percent of time items are given: 25
      Maximum number or items to give: 3
      Random Item 1: 265
      Random Item 2: 263
      Random Item 3: 340
    Spells:
      Award all players: true
      Random spells for finding diamonds: true
      Spell strength (1-5): 3
      Percent of time spells are casted: 100
      Messages:
        Jump: You are as weightless as a feather.
        Speed: You feel as swift as the wind.
        Resistance: You feel a force field surround you.
        Fire Resistance: You no longer fear the flames.
        Water Breathing: The sea calls out to you.
        Regeneration: A regenerative force embraces you.
        Fast Digging: Haste makes waste.
        Strength: You feel a strength rise up within you.
  Broadcasts:
    Broadcasted Blocks:
    Options:
      Message: "@Prefix@ @Player@ found @Number@ @BlockName@"
      Use player nicknames: false
      Use classic ore colors for ores: true
  Logging:
    Trap breaks: true
    Light Level Violations: false
    Log all diamond ore breaks: false
    Clean log (all ores): false
  Enabled Worlds:
  Admin Messages:
    Admin Message Blocks:
  MySQL:
    Enabled: false
    Username: root
    Password: bacon
    DatabaseName: minecraft
    URL: localhost
    Port: 3306
    Prefix: fd
  Debug:
    Enabled: false
  Metrics:
    Enabled: true
