Found Diamonds Configuration:
  Main:
    Disable in creative mode: true
    Disable ore mining in total darkness: true
    Give OPs all permissions: false
  Traps:
    Kick players on trap break: true
    Ban players on trap break: false
    Admin alerts on all trap breaks: false
    Kick message: You broke a FoundDiamonds trap block.
  Awards:
    Items:
      Random items for finding diamonds: false
      Percent of time awards are given: 25
      Random Item 1: 265
      Random Item 2: 263
      Random Item 3: 341
    Spells:
      Random spells for finding diamonds: true
      Spell strength (1-5): 5
      Percent of time spells are casted: 25
  Broadcasts:
    Diamond Ore: true
    Gold Ore: true
    Lapis Ore: true
    Redstone Ore: false
    Iron Ore: false
    Coal Ore: false
    Mossy Cobblestone: false
    Obsidian: false
    Message: '@Player@ found @Number@ @BlockName@'
    Use player nicknames: false
    Include [FD] Prefix: true
  Logging:
    Log all diamond ore breaks: false
  Enabled Worlds:
  - world
  Admin Messages:
    Diamond Ore: false
    Gold Ore: false
    Lapis Ore: false
    Iron Ore: false
