name: FoundDiamonds
version: 3.1.1
main: me.itsatacoshop247.FoundDiamonds.FoundDiamonds
author: itsatacoshop247, SeeD419
commands:
   fd:
     description: Shows the main menu
   founddiamonds:
     description: Shows the main menu